In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
import graphviz
from sklearn.tree import export_graphviz
from sklearn.tree import DecisionTreeClassifier

In [2]:
#Load Train Data
train_data = pd.read_csv(r'C:\Users\Pichau\Área de Trabalho\Kaggle\Competitions\House Prices\Data\train.csv')
train_data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [3]:
#Dropping columns with low number of non-null registers
train_data = train_data.drop(columns = ['Alley','MasVnrType','FireplaceQu','PoolQC','Fence','MiscFeature',], axis = 1 )
train_data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,0,0,0,0,12,2008,WD,Normal,250000

In [4]:
categorical_columns = train_data.select_dtypes(include =['object'])

In [5]:
label_encoder = LabelEncoder()
for column in categorical_columns.columns:
    train_data[column] = label_encoder.fit_transform(train_data[column])
train_data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,3,65.0,8450,1,3,3,0,4,...,0,0,0,0,0,2,2008,8,4,208500
1,2,20,3,80.0,9600,1,3,3,0,2,...,0,0,0,0,0,5,2007,8,4,181500
2,3,60,3,68.0,11250,1,0,3,0,4,...,0,0,0,0,0,9,2008,8,4,223500
3,4,70,3,60.0,9550,1,0,3,0,0,...,272,0,0,0,0,2,2006,8,0,140000
4,5,60,3,84.0,14260,1,0,3,0,2,...,0,0,0,0,0,12,2008,8,4,250000

In [6]:
median_values = train_data.median()
train_data = train_data.fillna(median_values)

In [7]:
X_train = train_data.iloc[:,1:74]
Y_train = train_data.iloc[:,74]

In [8]:
modelo = DecisionTreeClassifier()
modelo.fit(X_train, Y_train)

DecisionTreeClassifier()

In [9]:
test_data = pd.read_csv(r'C:\Users\Pichau\Área de Trabalho\Kaggle\Competitions\House Prices\Data\test.csv')
test_data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [10]:
test_data = test_data.drop(columns = ['Alley','MasVnrType','FireplaceQu','PoolQC','Fence','MiscFeature',], axis = 1 )

In [11]:
categorical_colums = test_data.select_dtypes(include =['object'])

In [12]:
label_encoder = LabelEncoder()
for column in categorical_columns.columns:
    test_data[column] = label_encoder.fit_transform(test_data[column])
test_data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,2,80.0,11622,1,3,3,0,4,...,0,0,0,120,0,0,6,2010,8,4
1,1462,20,3,81.0,14267,1,0,3,0,0,...,36,0,0,0,0,12500,6,2010,8,4
2,1463,60,3,74.0,13830,1,0,3,0,4,...,34,0,0,0,0,0,3,2010,8,4
3,1464,60,3,78.0,9978,1,0,3,0,4,...,36,0,0,0,0,0,6,2010,8,4
4,1465,120,3,43.0,5005,1,0,1,0,4,...,82,0,0,144,0,0,1,2010,8,4

In [13]:
median_values = test_data.median()
test_data_dummies = test_data.fillna(median_values)

In [14]:
X_test = test_data_dummies.iloc[:,1:74]

In [15]:
previsoes = modelo.predict(X_test)

In [16]:
previsoes = pd.DataFrame(previsoes)

In [17]:
previsoes = previsoes.rename(columns={0:'SalePrice'})
previsoes.head()

   SalePrice
0     122000
1     149900
2     192000
3     192000
4     176000

In [18]:
previsoes_final = pd.concat([test_data.iloc[:, 0], previsoes], axis=1)
previsoes_final.head()

     Id  SalePrice
0  1461     122000
1  1462     149900
2  1463     192000
3  1464     192000
4  1465     176000

In [20]:
previsoes_final.to_csv(r'C:\Users\Pichau\OneDrive\Área de Trabalho\Kaggle\Competitions\House Prices\Predict\previsoes_final_decision_tree.csv',index=False)

In [21]:
export_graphviz(modelo, out_file='tree.dot')